twenty_three/ancestry/urls.py
from django.conf.urls import patterns, url
from ancestry import views

urlpatterns = patterns('ancestry.views',

    url(r'^$', 'home', name='home'),
    url(r'^login/$', 'api_login', name='api_login'),
    url(r'^logout/$', 'api_logout', name='api_logout'),
    url(r'^callback/$', 'api_callback', name='api_callback'),
    url(r'^haplogroups/$', views.HaplogroupsAPIView.as_view(), name='haplogroups'),
    url(r'^ancestry/$', views.AncestryAPIView.as_view(), name='ancestry'),
    url(r'^neanderthal/$', views.NeanderthalAPIView.as_view(), name='neanderthal'),
    url(r'^genotypes/$', views.GenotypesAPIView.as_view(), name='genotypes')
)

twenty_three/geneology/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'geneology.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('ancestry.urls', namespace='ancestry')),
                       
    url(r'^admin/', include(admin.site.urls)),
)

twenty_three/ancestry/models.py
from django.db import models

# Create your models here.

twenty_three/ancestry/views.py
import requests

from django.shortcuts import redirect, render
from django.conf import settings

from rest_framework.response import Response
from rest_framework.views import APIView


def home(request):
    data = {
        'logged_in': 'access_token' in request.session
    }
    return render(request, 'ancestry/home.html', data)


def api_login(request):
    return redirect('https://api.23andme.com/authorize/?'
                    + 'redirect_uri='+settings.GENEOLOGY['redirect_uri']
                    + '&response_type=code'
                    + '&client_id='+settings.GENEOLOGY['client_id']
                    + '&scope='+settings.GENEOLOGY['scope'])


def api_logout(request):
    del request.session['access_token']
    del request.session['user_id']

    return redirect('ancestry:home')


def api_callback(request):
    if 'code' in request.GET:
        post_data = {
            'client_id': settings.GENEOLOGY['client_id'],
            'client_secret': settings.GENEOLOGY['client_secret'],
            'grant_type': 'authorization_code',
            'code': request.GET['code'],
            'redirect_uri': settings.GENEOLOGY['redirect_uri'],
            'scope': settings.GENEOLOGY['scope'],
        }
        r = requests.post('https://api.23andme.com/token/', data=post_data)

        response = r.json()

        request.session['access_token'] = response['access_token']

    return redirect('ancestry:home')


def get_headers(request):
    return {
        'Authorization': 'Bearer '+request.session['access_token']
    }


def get_id(request):
    if 'user_id' in request.session:
        return request.session['user_id']
    else:
        r = requests.get('https://api.23andme.com/1/user/',
                         headers=get_headers(request))
        request.session['user_id'] = r.json()['profiles'][0]['id']
        return request.session['user_id']


class HaplogroupsAPIView(APIView):

    def get(self, request, *args, **kwargs):

        r = requests.get('https://api.23andme.com/1/haplogroups/{0}/'.format(get_id(request)),
                         headers=get_headers(request))

        return Response(r.json())


class AncestryAPIView(APIView):

    def get(self, request, *args, **kwargs):

        r = requests.get('https://api.23andme.com/1/ancestry/{0}/'.format(get_id(request)),
                         headers=get_headers(request))

        return Response(r.json())


class NeanderthalAPIView(APIView):

    def get(self, request, *args, **kwargs):

        r = requests.get('https://api.23andme.com/1/neanderthal/{0}/'.format(get_id(request)),
                         headers=get_headers(request))

        return Response(r.json())


class GenotypesAPIView(APIView):

    def get(self, request, *args, **kwargs):

        locations = [
            'rs2853518',
            'i3001947',
            'i5050606',
        ]
        params = {
            'locations': ' '.join(locations)
        }

        r = requests.get('https://api.23andme.com/1/genotypes/{0}/'.format(get_id(request)),
                         headers=get_headers(request),
                         params=params)

        return Response(r.json())

twenty_three/ancestry/templates/ancestry/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>23andMe API test</title>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
                
                <!-- Bootstrap -->
                <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
                    
                    <!-- Move the body down to accomodate the navbar -->
                    <style>
                        body {
                            padding-top: 70px;
                            padding-bottom: 20px;
                        }
                    </style>
                    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'ancestry:home' %}">23andMe API test</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if logged_in %}
                        <li><a href="{% url 'ancestry:api_logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'ancestry:api_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.navbar-collapse -->
            </div>
        </div>
        
        <div class="container">
            
            <div class="jumbotron text-center">
                <h1>23andMe API test</h1>
                {% if logged_in %}
                <br /><br />
                <a href="{% url 'ancestry:haplogroups' %}" class="btn btn-lg btn-primary">Haplogroups</a>
                <a href="{% url 'ancestry:ancestry' %}" class="btn btn-lg btn-primary">Ancestry</a>
                <a href="{% url 'ancestry:neanderthal' %}" class="btn btn-lg btn-primary">Neanderthal</a>
                <a href="{% url 'ancestry:genotypes' %}" class="btn btn-lg btn-primary">Genotypes</a>
                {% endif %}
            </div>
            
            <hr>
            
            <footer>
                <p>&copy; Clark Perkins 2014</p>
            </footer>
        </div> <!-- /container -->
        
        
        <!-- Bootstrap core JavaScript
         ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>